---
- name: "Playbook 3: Kopia zapasowa AdGuard Home"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    adguard_data_path: /adguardhome/AdGuardHome
    adguard_config_path: /adguardhome/AdGuardHome/AdGuardHome.yaml
    adguard_work_dir: /adguardhome/AdGuardHome/data
    backup_destination_host: localhost
    backup_destination_path: /home/semaphore/backup/adguard
    timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"

  tasks:
    - name: Backup AdGuard Home block
      block:
        - name: Utwórz katalog tymczasowy na kopię zapasową
          file:
            path: /tmp/adguard_backup_{{ timestamp }}
            state: directory
            mode: '0700'

        - name: Zatrzymaj AdGuard Home
          systemd:
            name: AdGuardHome
            state: stopped
          register: adguard_stopped
          ignore_errors: yes

        - name: Skopiuj pliki konfiguracyjne AdGuard Home
          copy:
            src: "{{ item }}"
            dest: /tmp/adguard_backup_{{ timestamp }}/
            remote_src: yes
            mode: preserve
          loop:
            - "{{ adguard_config_path }}"
          register: config_backup

        - name: Skopiuj katalog danych AdGuard Home
          synchronize:
            src: "{{ adguard_work_dir }}/"
            dest: /tmp/adguard_backup_{{ timestamp }}/data/
            mode: pull
          delegate_to: "{{ inventory_hostname }}"
          register: data_backup

        - name: Uruchom AdGuard Home po utworzeniu kopii
          systemd:
            name: AdGuardHome
            state: started
          when: adguard_stopped is succeeded

        - name: Utwórz archiwum kopii zapasowej
          archive:
            path: /tmp/adguard_backup_{{ timestamp }}
            dest: /tmp/adguard_backup_{{ timestamp }}.tar.gz
            format: gz
          register: archive_created

        - name: Utwórz katalog docelowy na serwerze Semaphore
          file:
            path: "{{ backup_destination_path }}"
            state: directory
            mode: '0777'
          delegate_to: localhost
          become: false

        - name: Prześlij kopię zapasową do serwera Semaphore
          synchronize:
            src: /tmp/adguard_backup_{{ timestamp }}.tar.gz
            dest: "{{ backup_destination_path }}/"
            mode: pull
          delegate_to: localhost
          become: false
          register: backup_transfer

        - name: Wyczyść pliki tymczasowe
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /tmp/adguard_backup_{{ timestamp }}
            - /tmp/adguard_backup_{{ timestamp }}.tar.gz

      rescue:
        - name: Uruchom AdGuard Home w przypadku błędu
          systemd:
            name: AdGuardHome
            state: started
          ignore_errors: yes