---
- name: "Playbook 2: Aktualizacja Systemu Operacyjnego"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  handlers:
    - name: Reboot if required
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Reboot initiated by Ansible after system update"
      when: reboot_required.stat.exists | default(false)

  tasks:
    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
      register: apt_upgrade_result
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (Debian/Ubuntu)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
