---
- name: "Playbook 2: Aktualizacja Systemu Operacyjnego"
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  handlers:
    - name: Restart jesli wymagany
      ansible.builtin.reboot:
        reboot_timeout: 300
        msg: "Restart zainicjowany przez Ansible po aktualizacji systemu"
      when: reboot_required.stat.exists | default(false)

  tasks:
    - name: Aktualizacja cache pakietow
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Aktualizacja wszystkich pakietow apt
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
      register: apt_upgrade_result

    - name: Aktualizacja pakietow snap
      ansible.builtin.command:
        cmd: snap refresh
      register: snap_refresh_result
      changed_when: "'All snaps up to date' not in snap_refresh_result.stderr"
      failed_when: false

    - name: Sprawdzenie czy restart jest wymagany
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required
      notify: Restart jesli wymagany
